apiVersion: v1
kind: Service
metadata:
  name: local-app1-service
  labels:
    app: local-app1
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: local-app1
