apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-app5
spec:
  revisionHistoryLimit: 1      
  selector:
    matchLabels:
      app: local-app5
  # replicas: 1
  template:
    metadata:
      labels:
        app: local-app5
        version: "1"
    spec:
      containers:
      - name: local-app5
        # image: traefik/whoami
        image: containous/whoami
        imagePullPolicy: IfNotPresent
        resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 200m
              memory: 500Mi
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3              