apiVersion: v1
kind: Service
metadata:
  name: local-app5-service
  labels:
    app: local-app5
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: local-app5