apiVersion: apps/v1
kind: Deployment
metadata:
  name: local-web1
spec:
  revisionHistoryLimit: 1      
  selector:
    matchLabels:
      app: local-web1
  # replicas: 1
  template:
    metadata:
      labels:
        app: local-web1
    spec:
      containers:
      - name: local-web1
        image: traefik/whoami
        imagePullPolicy: IfNotPresent
