apiVersion: v1
kind: Service
metadata:
  name: staging-web-service
  labels:
    app: staging-web
spec:
  type: NodePort
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: staging-web
