apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: local-
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: local
    #name: in-cluster
  project: default
  source:
    path: kustomization/local/deployments/web
    repoURL: https://github.com/dong-tran/git-opts.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - PruneLast=true
      - CreateNamespace=true
  revisionHistoryLimit: 1